<?php
namespace Team\Business\Block;
class Business extends \Magento\Framework\View\Element\Template{
    protected function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
}
